# Use TailwindCSS default color palette

[colors]
ansi = [
  '#0f172a', # black, slate.900
  '#f43f5e', # red, rose.500
  '#2dd4bf', # green, teal.400
  '#fcd34d', # yellow, amber.300
  '#3b82f6', # blue, blue.500
  '#f472b6', # magenta, pink.400
  '#38bdf8', # cyan, sky.400
  '#94a3b8', # white, slate.400
]
background = '#0f172a'
brights = [
  '#475569', # brblack, slate.600
  '#fb7185', # brred, rose.400
  '#5eead4', # brgreen, teal.300
  '#fde68a', # bryellow, amber.200
  '#60a5fa', # brblue, blue.400
  '#f9a8d4', # brmagenta, pink.300
  '#7dd3fc', # brcyan, sky.300
  '#f8fafc', # brwhite, slate.50
]
compose_cursor = '#fbbf24'
cursor_bg = '#f8fafc'
cursor_border = '#f8fafc'
cursor_fg = '#0f172a'
foreground = '#f8fafc'
scrollbar_thumb = '#334155'
selection_bg = 'rgba(49% 82.7% 98.8% 15%)' # sky.300 15%
selection_fg = 'none'
split = '#94a3b8'

[colors.indexed]

[colors.tab_bar]
background = '#1e293b'

[colors.tab_bar.active_tab]
bg_color = '#0f172a'
fg_color = '#38bdf8'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#1e293b'
fg_color = '#94a3b8'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#334155'
fg_color = '#cbd5e1'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#1e293b'
fg_color = '#94a3b8'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#334155'
fg_color = '#cbd5e1'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = "johanvx"
name = "Matataki"
origin_url = "https://github.com/johanvx/wezterm-config"
