# Use TailwindCSS default color palette

[colors]
ansi = [
  '#0f172a', # black, slate.900
  '#f43f5e', # red, rose.500
  '#2dd4bf', # green, teal.400
  '#facc15', # yellow, yellow.400
  '#38bdf8', # blue, sky.400
  '#f472b6', # magenta, pink.400
  '#67e8f9', # cyan, cyan.300
  '#cbd5e1', # white, slate.300
]
background = '#0f172a' # black, slate.900
brights = [
  '#64748b', # brblack, slate.500
  '#fb7185', # brred, rose.400
  '#5eead4', # brgreen, teal.300
  '#fde047', # bryellow, yellow.300
  '#7dd3fc', # brblue, sky.300
  '#f9a8d4', # brmagenta, pink.300
  '#a5f3fc', # brcyan, cyan.200
  '#f1f5f9', # brwhite, slate.100
]
compose_cursor = '#38bdf8' # blue, sky.400
cursor_bg = '#f1f5f9' # brwhite, slate.100
cursor_border = '#f1f5f9' # brwhite, slate.100
cursor_fg = '#0f172a' # black, slate.900
foreground = '#cbd5e1' # white, slate.300
scrollbar_thumb = '#334155' # slate.700
selection_bg = 'rgba(49% 83% 99% 15%)' # brcyan, sky.300 15%
selection_fg = 'none'
split = '#cbd5e1' # white, slate.300

[colors.indexed]

[colors.tab_bar]
background = '#1e293b' # slate.800

[colors.tab_bar.active_tab]
bg_color = '#0f172a'  # black, slate.900
fg_color = '#38bdf8'  # cyan, sky.400
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#1e293b'  # slate.800
fg_color = '#64748b'  # brblack, slate.500
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#334155'  # slate.700
fg_color = '#cbd5e1'  # white, slate.300
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#1e293b'  # slate.800
fg_color = '#64748b'  # brblack, slate.500
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#334155'  # slate.700
fg_color = '#cbd5e1'  # white, slate.300
intensity = 'Bold'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = "johanvx"
name = "Matataki"
origin_url = "https://github.com/johanvx/wezterm-config"
